name: nightly-push

on:
  workflow_run:
    workflows: ["nightly"]
    types: [completed]

jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_BOT_WEBHOOK_LISA_ZEPHYR}}
        with:
          msgtype: news
          articles: '[{"title":"NIGHTLY 集成测试","description":"一切正常","url":"URL","picurl":"https://cdn.iflyos.cn/public/lisa-binary/zzsm.jpg"}]'

  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_BOT_WEBHOOK_LISA_ZEPHYR}}
        with:
          msgtype: news
          articles: '[{"title":"NIGHTLY 集成测试","description":"炸了","url":"URL","picurl":"https://cdn.iflyos.cn/public/lisa-binary/tufa.jpg"}]'
